--1.	Create a list of employee names and their full addresses using the INNER JOIN.
SELECT E.FIRSTNAME, E.LASTNAME, A.ADDRESSLINE1, A.ADDRESSLINE2, A.CITY, A.STATE, A.ZIP1, A.ZIP2
FROM EMPLOYEES E
INNER JOIN ADDRESSES A
ON E.EMPLOYEEID = A.EMPLOYEEID

--2.	Create a list of employee names and their full addresses using the INNER JOIN for employees 
--		who live either in Massachusetts or California.

SELECT E.FIRSTNAME, E.LASTNAME, A.ADDRESSLINE1, A.ADDRESSLINE2, A.CITY, A.STATE, A.ZIP1, A.ZIP2
FROM EMPLOYEES E
INNER JOIN ADDRESSES A
ON E.EMPLOYEEID = A.EMPLOYEEID
WHERE UPPER(A.STATE) = 'MA' OR UPPER(A.STATE) = 'CA'

--3.	Create an example of a Cartesian product using the Employees and Addresses table.
SELECT E.FIRSTNAME, E.LASTNAME, A.ADDRESSLINE1, A.ADDRESSLINE2, A.CITY, A.STATE, A.ZIP1, A.ZIP2
FROM EMPLOYEES E
CROSS JOIN ADDRESSES A

-- 4.	Use a LEFT OUTER JOIN to list all employee first and last names 
--		as well as the gender and birthdates of their dependents if they have any.
SELECT E.FIRSTNAME, E.LASTNAME, D.FIRSTNAME, D.LASTNAME, D.GENDER, D.BIRTHDATE
FROM EMPLOYEES E
LEFT OUTER JOIN DEPENDENTS D
ON D.EMPLOYEEID = E.EMPLOYEEID

-- 5.	Use a RIGHT OUTER JOIN to list all employee first and last names 
--		as well as the gender and birthdates of their dependents if they have any 
--		(Same as above but change location of tables).
SELECT E.FIRSTNAME, E.LASTNAME, D.FIRSTNAME, D.LASTNAME, D.GENDER, D.BIRTHDATE
FROM DEPENDENTS D
RIGHT OUTER JOIN EMPLOYEES E
ON D.EMPLOYEEID = E.EMPLOYEEID

-- 6.	Use a SELF JOIN to select the employee first name, last name, 
--		title as well as the manager's first name, last name and title.
SELECT E.FIRSTNAME, E.LASTNAME, E.TITLE, M.FIRSTNAME MANAGER_FIRST_NAME, M.LASTNAME MANAGER_LAST_NAME, M.TITLE MANAGER_TITLE
FROM EMPLOYEES E
INNER JOIN EMPLOYEES M
	ON E.MANAGERID = M.EMPLOYEEID

-- 7.	Retrieve the employee first name, last name, department name and group name for the employee named Gail Erickson.
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME, D.GROUPNAME
FROM EMPLOYEES E
JOIN EMPLOYEESDEPARTMENTS ED ON E.EMPLOYEEID = ED.EMPLOYEEID
JOIN DEPARTMENTS D ON D.DEPARTMENTID = ED.DEPARTMENTID
WHERE UPPER(E.FIRSTNAME) = 'GAIL' AND UPPER(E.LASTNAME) = 'ERICKSON'

-- 8.	Retrieve the employee first name, last name, address, city, state, zip, 
--		department name and group name for the employee named David Bradley.
SELECT 	E.FIRSTNAME, E.LASTNAME,
		A.ADDRESSLINE1, A.ADDRESSLINE2, A.CITY, A.STATE, A.ZIP1, A.ZIP2,
		D.DEPARTMENTNAME, D.GROUPNAME
FROM EMPLOYEES E
JOIN ADDRESSES A ON E.EMPLOYEEID = A.EMPLOYEEID
JOIN EMPLOYEESDEPARTMENTS ED ON E.EMPLOYEEID = ED.EMPLOYEEID
JOIN DEPARTMENTS D ON D.DEPARTMENTID = ED.DEPARTMENTID
WHERE UPPER(E.FIRSTNAME) = 'DAVID' AND UPPER(E.LASTNAME) = 'BRADLEY' 

-- 9.	Retrieve the employee first name, last name, dependent first name, last name and gender for female dependents.
SELECT E.FIRSTNAME, E.LASTNAME, D.FIRSTNAME DEPENDENT_F_NAME, D.LASTNAME DEPENDENT_L_NAME, D.GENDER, D.BIRTHDATE
FROM EMPLOYEES E
LEFT OUTER JOIN DEPENDENTS D
ON D.EMPLOYEEID = E.EMPLOYEEID
WHERE D.GENDER = 'F'

-- 10.	Retrieve the employee first name, last name, dependent first name, last name, birth date 
--		for dependents who have birth dates less than or equal to 11/02/2008. 
SELECT E.FIRSTNAME, E.LASTNAME, D.FIRSTNAME DEPENDENT_F_NAME, D.LASTNAME DEPENDENT_L_NAME, D.GENDER, D.BIRTHDATE
FROM EMPLOYEES E
LEFT OUTER JOIN DEPENDENTS D
ON D.EMPLOYEEID = E.EMPLOYEEID
WHERE D.BIRTHDATE <= '11/02/2008'::DATE

-- 11.	Use LEFT OUTER JOINS to list all Employees, their Department Names, and their dependent names, if any.
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME, D.GROUPNAME, Y.FIRSTNAME DEPENDENT_F_NAME, Y.LASTNAME DEPENDENT_L_NAME
FROM EMPLOYEES E
LEFT OUTER JOIN EMPLOYEESDEPARTMENTS ED ON E.EMPLOYEEID = ED.EMPLOYEEID
LEFT OUTER JOIN DEPARTMENTS D ON D.DEPARTMENTID = ED.DEPARTMENTID
LEFT OUTER JOIN DEPENDENTS Y ON Y.EMPLOYEEID = E.EMPLOYEEID

-- 12.	Use RIGHT OUTER JOINS to list all Employees, their Department Names, and their dependent names, like you did in the question above.
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME, D.GROUPNAME, Y.FIRSTNAME DEPENDENT_F_NAME, Y.LASTNAME DEPENDENT_L_NAME
FROM  DEPENDENTS Y
RIGHT OUTER JOIN EMPLOYEES E ON Y.EMPLOYEEID = E.EMPLOYEEID
RIGHT OUTER JOIN EMPLOYEESDEPARTMENTS ED ON E.EMPLOYEEID = ED.EMPLOYEEID
RIGHT OUTER JOIN DEPARTMENTS D ON D.DEPARTMENTID = ED.DEPARTMENTID

-- 13.	Retrieve the employee first name, last name, dependent first name, last name and gender for dependents who were born in or before 1998.
SELECT E.FIRSTNAME, E.LASTNAME, D.FIRSTNAME DEPENDENT_F_NAME, D.LASTNAME DEPENDENT_L_NAME, D.GENDER, D.BIRTHDATE
FROM EMPLOYEES E
LEFT OUTER JOIN DEPENDENTS D
ON D.EMPLOYEEID = E.EMPLOYEEID
WHERE D.BIRTHDATE <= '12/31/1998'::DATE

-- 14.	Retrieve all employees belonging to the department “Marketing” using INNER JOINS.

SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEESDEPARTMENTS ED ON E.EMPLOYEEID = ED.EMPLOYEEID
INNER JOIN DEPARTMENTS D ON D.DEPARTMENTID = ED.DEPARTMENTID
WHERE UPPER(D.DEPARTMENTNAME) = 'MARKETING'

-- 15.	Retrieve the first name, last name, and title of the manager responsible for the Employee 
--		with the first name “Ben” and last name “Miller”.
SELECT M.FIRSTNAME, M.LASTNAME, M.TITLE
FROM EMPLOYEES M
INNER JOIN EMPLOYEES E
	ON M.EMPLOYEEID = E.MANAGERID
WHERE UPPER(E.FIRSTNAME) = 'BEN' AND UPPER(E.LASTNAME) = 'MILLER'
